CREATE TABLE SEGMENTO (
  CODSEGMENTO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO   varchar(255) NOT NULL UNIQUE, 
  PRIMARY KEY (CODSEGMENTO));
CREATE TABLE CEP (
  CEP       varchar(9) NOT NULL, 
  CIDADE    varchar(255) NOT NULL, 
  BAIRRO    varchar(255) NOT NULL, 
  RUA       varchar(255) NOT NULL, 
  CODESTADO int(10) NOT NULL, 
  PRIMARY KEY (CEP));
CREATE TABLE CONTATO (
  CODCONTATO int(10) NOT NULL AUTO_INCREMENT, 
  NOME       varchar(100), 
  TELEFONE   varchar(20) NOT NULL UNIQUE, 
  CODCLIENTE int(10) NOT NULL, 
  PRIMARY KEY (CODCONTATO));
CREATE TABLE LINK_CLIENTE (
  CODLINK_CLIENTE int(10) NOT NULL AUTO_INCREMENT, 
  QUANTIDADE      int(10) DEFAULT 0 NOT NULL, 
  CODCLIENTE      int(10) NOT NULL, 
  CODLINK         int(10) NOT NULL, 
  PRIMARY KEY (CODLINK_CLIENTE));
CREATE TABLE TIPO_INFORMACAO (
  CODTIPOINFORMACAO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO         varchar(255) NOT NULL UNIQUE, 
  PRIMARY KEY (CODTIPOINFORMACAO));
CREATE TABLE INFORMACAO (
  CODINFORMACAO     int(10) NOT NULL AUTO_INCREMENT, 
  OBSERVACAO        varchar(255) NOT NULL, 
  DATA              date NOT NULL, 
  CODTIPOINFORMACAO int(10) NOT NULL, 
  CODUSUARIO        int(10) NOT NULL, 
  PRIMARY KEY (CODINFORMACAO));
CREATE TABLE PONTO (
  CODPONTO            int(10) NOT NULL AUTO_INCREMENT, 
  TIPO                char(1) NOT NULL, 
  OBSERVACAO          varchar(255), 
  DATA_ENTRADA        datetime NOT NULL, 
  DATA_SAIDA          datetime NULL, 
  DATA_ALMOCO_ENTRADA datetime NULL, 
  DATA_ALMOCO_SAIDA   datetime NULL, 
  CODUSUARIO          int(10) NOT NULL, 
  PRIMARY KEY (CODPONTO));
CREATE TABLE AVALIACAO (
  CODAVALIACAO     int(10) NOT NULL AUTO_INCREMENT, 
  NOTA_ATENDIMENTO int(10) NOT NULL, 
  NOTA_APLICATIVO  int(10) NOT NULL, 
  PRIMARY KEY (CODAVALIACAO));
CREATE TABLE LINK (
  CODLINK       int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO     varchar(255) NOT NULL UNIQUE, 
  CODAPLICATIVO int(10) NOT NULL, 
  PRIMARY KEY (CODLINK));
CREATE TABLE LOG (
  CODLOG      int(10) NOT NULL AUTO_INCREMENT, 
  DATA_EVENTO datetime NOT NULL, 
  DESCRICAO   varchar(100) NOT NULL, 
  TABELA      varchar(50) NOT NULL, 
  CODUSUARIO  int(10) NOT NULL, 
  PRIMARY KEY (CODLOG));
CREATE TABLE ENDERECO (
  CODENDERECO int(10) NOT NULL AUTO_INCREMENT, 
  NUMERO      int(10) NOT NULL, 
  COMPLEMENTO varchar(255), 
  CODCLIENTE  int(10) NOT NULL, 
  CEP         varchar(9) NOT NULL, 
  PRIMARY KEY (CODENDERECO));
CREATE TABLE EMAIL (
  CODEMAIL   int(10) NOT NULL AUTO_INCREMENT, 
  EMAIL      varchar(255) NOT NULL, 
  SMTP       varchar(255) NOT NULL, 
  PORTA      int(10) NOT NULL, 
  NOME       varchar(255) NOT NULL, 
  SENHA      varchar(255) NOT NULL, 
  ASSINATURA varchar(255) NOT NULL, 
  PRIMARY KEY (CODEMAIL));
CREATE TABLE EMPRESA (
  CODEMPRESA    int(10) NOT NULL AUTO_INCREMENT, 
  NOME_FANTASIA varchar(255) NOT NULL UNIQUE, 
  CNPJ_CPF      varchar(20) NOT NULL UNIQUE, 
  TELEFONE      varchar(20) NOT NULL, 
  CODEMAIL      int(10) NOT NULL, 
  PRIMARY KEY (CODEMPRESA));
CREATE TABLE STATUS (
  CODSTATUS int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODSTATUS));
CREATE TABLE TIPO_USUARIO (
  CODTIPOUSUARIO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO      varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODTIPOUSUARIO));
CREATE TABLE USUARIO (
  CODUSUARIO     int(10) NOT NULL AUTO_INCREMENT, 
  NOME           varchar(255) NOT NULL, 
  CPF            varchar(14) NOT NULL UNIQUE, 
  SEXO           char(1) NOT NULL, 
  EMAIL          varchar(255) NOT NULL UNIQUE, 
  USUARIO        varchar(255) NOT NULL UNIQUE, 
  SENHA          varchar(255) NOT NULL, 
  FOTO           varchar(255) NOT NULL, 
  CODTIPOUSUARIO int(10) NOT NULL, 
  BLOQUEADO      char(1) NOT NULL, 
  PRIMARY KEY (CODUSUARIO));
CREATE TABLE PRIORIDADE (
  CODPRIORIDADE int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO     varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODPRIORIDADE));
CREATE TABLE ORIGEM (
  CODORIGEM int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODORIGEM));
CREATE TABLE TIPO_ATENDIMENTO (
  CODTIPOATENDIMENTO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO          varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODTIPOATENDIMENTO));
CREATE TABLE ATENDIMENTO (
  CODATENDIMENTO     int(10) NOT NULL AUTO_INCREMENT, 
  DATA_ABERTURA      datetime NOT NULL, 
  DATA_AGENDAMENTO   datetime NULL, 
  DATA_FECHAMENTO    datetime NULL, 
  DATA_CANCELAMENTO  datetime NULL, 
  DATA_INICIO        datetime NULL, 
  DATA_FIM           datetime NULL, 
  SOLICITANTE        varchar(100), 
  PROBLEMA_INFORMADO varchar(255) NOT NULL, 
  PROBLEMA_DETECTADO varchar(255), 
  PROBLEMA_PENDENCIA varchar(255), 
  PROBLEMA_SOLUCAO   varchar(255), 
  PENDENCIA          char(1) NOT NULL, 
  DATA_SOLUCAO       datetime NULL, 
  CODTIPOATENDIMENTO int(10) NOT NULL, 
  CODORIGEM          int(10) NOT NULL, 
  CODPRIORIDADE      int(10) NOT NULL, 
  CODUSUARIO         int(10) NOT NULL, 
  CODCLIENTE         int(10) NOT NULL, 
  CODSTATUS          int(10) NOT NULL, 
  CODAVALIACAO       int(10) NOT NULL, 
  PRIMARY KEY (CODATENDIMENTO));
CREATE TABLE UF (
  CODESTADO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO char(2) NOT NULL, 
  PRIMARY KEY (CODESTADO));
CREATE TABLE APLICATIVO (
  CODAPLICATIVO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO     varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODAPLICATIVO));
CREATE TABLE CLIENTE (
  CODCLIENTE         int(10) NOT NULL AUTO_INCREMENT, 
  REFERENCIA         int(10), 
  RAZAO_SOCIAL       varchar(255) NOT NULL UNIQUE, 
  NOME_FANTASIA      varchar(255) NOT NULL, 
  RESPONSAVEL        varchar(100) NOT NULL, 
  CNPJ_CPF           varchar(255) NOT NULL UNIQUE, 
  INSCRICAO_ESTADUAL varchar(100) NOT NULL, 
  EMAIL              varchar(255) NOT NULL UNIQUE, 
  BLOQUEADO          char(1) NOT NULL, 
  DATA_ATUALIZACAO   datetime NULL, 
  CODTIPOCLIENTE     int(10) NOT NULL, 
  PRIMARY KEY (CODCLIENTE));
ALTER TABLE CLIENTE ADD INDEX FKCLIENTE58336 (CODTIPOCLIENTE), ADD CONSTRAINT FKCLIENTE58336 FOREIGN KEY (CODTIPOCLIENTE) REFERENCES SEGMENTO (CODSEGMENTO);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT837458 (CODSTATUS), ADD CONSTRAINT FKATENDIMENT837458 FOREIGN KEY (CODSTATUS) REFERENCES STATUS (CODSTATUS);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT382556 (CODCLIENTE), ADD CONSTRAINT FKATENDIMENT382556 FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT289250 (CODUSUARIO), ADD CONSTRAINT FKATENDIMENT289250 FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO);
ALTER TABLE USUARIO ADD INDEX FKUSUARIO900738 (CODTIPOUSUARIO), ADD CONSTRAINT FKUSUARIO900738 FOREIGN KEY (CODTIPOUSUARIO) REFERENCES TIPO_USUARIO (CODTIPOUSUARIO);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT565725 (CODPRIORIDADE), ADD CONSTRAINT FKATENDIMENT565725 FOREIGN KEY (CODPRIORIDADE) REFERENCES PRIORIDADE (CODPRIORIDADE);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT252746 (CODORIGEM), ADD CONSTRAINT FKATENDIMENT252746 FOREIGN KEY (CODORIGEM) REFERENCES ORIGEM (CODORIGEM);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT799707 (CODTIPOATENDIMENTO), ADD CONSTRAINT FKATENDIMENT799707 FOREIGN KEY (CODTIPOATENDIMENTO) REFERENCES TIPO_ATENDIMENTO (CODTIPOATENDIMENTO);
ALTER TABLE EMPRESA ADD INDEX FKEMPRESA64388 (CODEMAIL), ADD CONSTRAINT FKEMPRESA64388 FOREIGN KEY (CODEMAIL) REFERENCES EMAIL (CODEMAIL);
ALTER TABLE ENDERECO ADD INDEX FKENDERECO434911 (CODCLIENTE), ADD CONSTRAINT FKENDERECO434911 FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);
ALTER TABLE LOG ADD INDEX FKLOG475992 (CODUSUARIO), ADD CONSTRAINT FKLOG475992 FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO);
ALTER TABLE ATENDIMENTO ADD INDEX FKATENDIMENT13905 (CODAVALIACAO), ADD CONSTRAINT FKATENDIMENT13905 FOREIGN KEY (CODAVALIACAO) REFERENCES AVALIACAO (CODAVALIACAO);
ALTER TABLE INFORMACAO ADD INDEX FKINFORMACAO28001 (CODUSUARIO), ADD CONSTRAINT FKINFORMACAO28001 FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO);
ALTER TABLE INFORMACAO ADD INDEX FKINFORMACAO160939 (CODTIPOINFORMACAO), ADD CONSTRAINT FKINFORMACAO160939 FOREIGN KEY (CODTIPOINFORMACAO) REFERENCES TIPO_INFORMACAO (CODTIPOINFORMACAO);
ALTER TABLE PONTO ADD INDEX FKPONTO238662 (CODUSUARIO), ADD CONSTRAINT FKPONTO238662 FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO);
ALTER TABLE LINK_CLIENTE ADD INDEX FKLINK_CLIEN891711 (CODLINK), ADD CONSTRAINT FKLINK_CLIEN891711 FOREIGN KEY (CODLINK) REFERENCES LINK (CODLINK);
ALTER TABLE LINK_CLIENTE ADD INDEX FKLINK_CLIEN212659 (CODCLIENTE), ADD CONSTRAINT FKLINK_CLIEN212659 FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);
ALTER TABLE LINK ADD INDEX FKLINK898337 (CODAPLICATIVO), ADD CONSTRAINT FKLINK898337 FOREIGN KEY (CODAPLICATIVO) REFERENCES APLICATIVO (CODAPLICATIVO);
ALTER TABLE ENDERECO ADD INDEX FKENDERECO113506 (CEP), ADD CONSTRAINT FKENDERECO113506 FOREIGN KEY (CEP) REFERENCES CEP (CEP);
ALTER TABLE CEP ADD INDEX FKCEP824559 (CODESTADO), ADD CONSTRAINT FKCEP824559 FOREIGN KEY (CODESTADO) REFERENCES UF (CODESTADO);
ALTER TABLE CONTATO ADD INDEX FKCONTATO287956 (CODCLIENTE), ADD CONSTRAINT FKCONTATO287956 FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);
