--INSERÇÃO DOS APLICATIVOS
INSERT INTO aplicativo (`CODAPLICATIVO`,`DESCRICAO`)
	VALUES (1,'ATS');
INSERT INTO aplicativo (`CODAPLICATIVO`,`DESCRICAO`)
	VALUES (2,'YUNES');

--INSERÇÃO DE LINKS
INSERT INTO `link` (`CODLINK`,`DESCRICAO`, `CODAPLICATIVO`) 
	VALUES (1,'START', 1);
INSERT INTO `link` (`CODLINK`,`DESCRICAO`, `CODAPLICATIVO`) 
	VALUES (2,'BUSINESS', 1);
INSERT INTO `link` (`CODLINK`,`DESCRICAO`, `CODAPLICATIVO`) 
	VALUES (3,'FATURAMENTO', 2);
INSERT INTO `link` (`CODLINK`,`DESCRICAO`, `CODAPLICATIVO`) 
	VALUES (4,'CADASTRO', 2);

--INSERÇÃO DAS ORIGENS

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('1','EMAIL');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('2','TELEFONE');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('3','SKYPE');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('4','VERBAL');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('5','WEB');



--INSERÇÃO DOS STATUS DO ATENDIMENTO

INSERT INTO status_atendimento (CODSTATUSATENDIMENTO, DESCRICAO) VALUES ('1','ABERTO');

INSERT INTO status_atendimento (CODSTATUSATENDIMENTO, DESCRICAO) VALUES ('2','EXECUCAO');

INSERT INTO status_atendimento (CODSTATUSATENDIMENTO, DESCRICAO) VALUES ('3','PENDENTE');

INSERT INTO status_atendimento (CODSTATUSATENDIMENTO, DESCRICAO) VALUES ('4','CONCLUIDO');

--INSERÇÃO DAS PRIORIDADES

INSERT INTO PRIORIDADE (CODPRIORIDADE, DESCRICAO) VALUES ('1','NORMAL');

INSERT INTO PRIORIDADE (CODPRIORIDADE, DESCRICAO) VALUES ('2','URGENTE');



--INSERÇÃO DAS TIPO ATENDIMENTO

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('1','SUPORTE');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('2','TREINAMENTO');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('3','REUNIAO');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('4','CONSULTORIA');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('5','ATUALIZACAO');



--INSERÇÃO DOS TIPO_USUARIO

INSERT INTO TIPO_USUARIO(CODTIPOUSUARIO, DESCRICAO) VALUES ('1','SUPORTE');

INSERT INTO TIPO_USUARIO(CODTIPOUSUARIO, DESCRICAO) VALUES ('2','ATENDENTE');

INSERT INTO TIPO_USUARIO(CODTIPOUSUARIO, DESCRICAO) VALUES ('3','GESTOR');
--INSERÇÕES DOS TIPO_INFORMACAO

INSERT INTO `tipo_informacao` (`CODTIPOINFORMACAO`,`DESCRICAO`) VALUES (1,'ELOGIO');
INSERT INTO `tipo_informacao` (`CODTIPOINFORMACAO`,`DESCRICAO`) VALUES (2,'DUVIDA');
INSERT INTO `tipo_informacao` (`CODTIPOINFORMACAO`,`DESCRICAO`) VALUES (3,'SUGESTÃO');
INSERT INTO `tipo_informacao` (`CODTIPOINFORMACAO`,`DESCRICAO`) VALUES (4,'RECLAMAÇÃO');

--INSERÇÕES DOS STATUS DE PESSOA
INSERT INTO status_pessoa (`DESCRICAO`) 
	VALUES ('BLOQUEADO');
INSERT INTO status_pessoa (`DESCRICAO`) 
	VALUES ('DESBLOQUEADO');

--INSERÇÕES DOS TIPOS DE PESSOA
INSERT INTO tipo_pessoa (`DESCRICAO`) 
	VALUES ('FISICA');
INSERT INTO tipo_pessoa (`DESCRICAO`) 
	VALUES ('JURIDICA');

--INSERÇÕES DOS SEGMENTOS
INSERT INTO segmento (`DESCRICAO`) 	VALUES ('LANCHONETE');




